export enum apiEndpoints {
  // authentication flow
  CONFIRMEMAIL = "WebUserBiodata/CheckUserByEmail",
  CONFIRMID = "WebUserBiodata/CheckUserById",
  LOGIN = "WebUserBiodata/Login",
  FORGOT_PASSWORD = "WebUserBiodata/ForgotPassword",
  PASSWORD_RESET = "WebUserBiodata/PasswordResset",
  CHANGE_PASSWORD = "WebUserBiodata/ChangeLoginPassword",
  UPDATE_SETTINGS = "WebUserBiodata/Update",
  CHANGE_LOGIN_PASSWORD = "WebUserBiodata/ChangeLoginPassword",

  // motor insurance
  MOTORINSURANCE = "VehiclePremiumPolicyHolder/GetByUserBiodataId",
  GET_ALL_PRODUCTS = "WebProduct/GetAll",
  GET_ALL_FIRM_PRODUCT_BY_ID = "WebFirmProduct/GetAllByProductId",
  GET_ALL_PRODUCT_PLANS_BY_ID = "WebFirmProduct/GetAllByProductPlanByProductAndFirmId",
  GET_ALL_YEAR = "VehicleYear/GetAll",
  GET_ALL_VEHICLE_TYPE = "WebVehicleType/GetAll",
  GET_ALL_VEHICLE_TYPE_BY_ID = "WebVehicleType/GetAllByFirmId",
  GET_ALL_VEHICLE_USUAGE = "WebVehicleUsageMode/GetAllActive",
  GET_ALL_BUS_Make = "WebBusMake/GetAll",
  GET_ALL_BUS_BY_ID = "WebBusModel/GetAllByBusMakeId?Id=",
  GET_ALL_SPECIAL_TYPE_Make = "WebSpecialTypeMake/GetAll",
  GET_ALL_SPECIAL_TYPE_BY_ID = "WebSpecialTypeModel/GetAllBySpecialTypeMakeId?Id=",
  GET_ALL_CAR_Make_BY_ID= "WebVehicleMake/GetAllByVehicleTypeId",
  GET_ALL_CAR_BY_ID = "WebVehicleModel/GetAllByVehicleTypeAndMakeId",
  GET_ALL_TRICYCLE_Make = "WebTricycleMake/GetAll",
  GET_ALL_TRICYCLE_BY_ID = "WebTricycleModel/GetAllByTricycleMakeId?Id=",
  GET_ALL_MOTORCYCLE_Make = "WebMotorCycleMake/GetAll",
  GET_ALL_MOTORCYCLE_BY_ID = "WebTricycleModel/GetAllByTricycleMakeId?Id=",
  GET_ALL_TRUCK_Make = "WebTruckMake/GetAll",
  GET_ALL_TRUCKS_BY_ID = "WebTruckModel/GetAllByTruckMakeId?Id=",
  GET_ALL_GENDER = "Gender/GetAll",
  GET_USER_BY_EMAIL = "WebUserBiodata/CheckUserByEmail",
  GET_LOCAL_GOV = "WebLocalGovernment/GetByStateId",
  GET_PREMIUM = "WebMotorInsurancePremium/GetByFirmProductId",
  GET_STATES = "WebState/GetAll",
  GET_PARTICULAR_PREMIUM = "WebMotorInsurancePremium/GetByIds",
  // GET_MOTOR_INSUR_COMISSION = "WebFirmCommissionPercentage/GetByFirmIdProductIdAndMotorPremiumTypeIdAndSalesType",
  GET_MOTOR_INSUR_COMISSION = "WebbespokeCommissionPercentage/GetByProductIdAndMotorPremiumTypeIdAndSalesType",
  ADD_VEHICLE = "PremiumPolicyNo/AddVehicle",
  VIEW_VEHICLE_CERT = "PremiumPolicyNo/VehiclePolicyDetailsOnly",
  VIEW_VEHICLE_TRANSACTION = "PremiumPolicyNo/VehicleDetailsWithTransactionId",
  PREMIUM_HOLDER_SUMMARY = "WebVehiclePremiumPolicyHolder/PolicyAndClaimDataByUserBiodataId",
  GET_ACTIVE_MOTOR_INSUR = "WebVehiclePremiumPolicyHolder/GetActiveByUserBiodataId",
  GET_INACTIVE_MOTOR_INSUR = "WebVehiclePremiumPolicyHolder/GetInActiveByUserBiodataId",
  GET_MOTOR_INSUR_CLAIM = "WebVehicleInsuranceClaim/GetByBiodataId",
  GET_MOTOR_INSUR_CLAIM_DETAILS = "WebVehicleInsuranceClaim",
  GET_MOTOR_INSUR_POLICY_DETAILS = "WebVehiclePremiumPolicyHolder/GetRegVehiclePolicyDetailsById",
  ADD_USER_BIODATA = "WebUserBiodata/AddNewUser",
  ADD_INSURED_USER_BIODATA = "WebUserBiodata/AddInsured",
  CHECK_POLICY_NO = "PremiumPolicyNo/CheckPolicyNumber",

  GET_SUBACCOUNTS = "WebFirmCommissionPercentage/GetAllDetailForSubAccount",

  // claim
  CONFIRM_POLICY_NUMBER = "PremiumPolicyNo/CheckPolicyNumberWithUserBiodataId",
  GET_CLAIM_VEHICLE = "WebVehicleInsuranceClaim/GetByPolicyNumber",
  GET_CLAIM_TYPE = "WebClaimsType/GetAll",
  ADD_CLAIM_NOTIFICATION = "WebVehicleInsuranceClaim/AddClaimNotification?obj=[object%20Object]",
  GET_USAGE_MODE = "WebVehicleUsageMode/GetAllActive",
  UPDATE_CLAIM = "WebVehicleInsuranceClaim/Update?obj=[object%20Object]",
  CONFIRM_SETTLEMENT = "WebVehicleInsuranceClaim/SettlementConfirmation",
  CHECK_POLICY_AND_VEHICLE_DETAILS = "WebVehicleInsuranceClaim/CheckPolicyAndVehicleDetails",
  CHECK_VEHICLE_DETAILS = "WebVehicleInsuranceClaim/CheckVehicleDetails",

  //Terms
  GET_POLICY_TERMS = "WebFirmProductTermsAndCondition/GetByFirmIdAndProductId",

  GET_FIRM_PRODUCT_FLEET_BY_ID = "WebFirmProduct/GetByFirmProductId",


  //AGENT
  ADD_AGENT = 'WebUserBiodata/AddAgent',
  AGENT_CONFIRMATION = 'WebUserBiodata/AccountConfirmation',
  ADD_AGENT_KYC = 'WebUserBiodata/AgentKYC',
  ADD_AGENT_GUARANTOR = 'WebUserBiodata/AgentGuarantor',

  GET_AGENT_DASHBOARD = 'WebVehiclePremiumPolicyHolder/PolicyAndClaimDataByUserBiodataId',
  GET_WALLET_OVERVIEW = 'WebWalletDeposit/WalletOverview',
  GET_PAYMENT_HISTORY = 'WebWalletDeposit/PaymentHistory',
  ADD_DEPOSIT = 'WebWalletDeposit/Add',
  GET_PAYMENT_BY_ID = 'WebWalletDeposit/PaymentHistoryById',
}
