// import AuthProvider from "@/context/AuthContext";
// import ScopedCssBaseline from "@mui/material/ScopedCssBaseline";
import type { AppProps } from "next/app";
import { QueryClient, QueryClientProvider } from "react-query";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import type { Metadata } from "next";
import "../../views/styles/globals.css";

export const metadata: Metadata = {
  title: "BOIIBOnline",
  description: "Generated by create next app",
};

const queryClient = new QueryClient({
  defaultOptions: {
    queries: {
      refetchOnWindowFocus: false,
      retry: 1,
    },
  },
});

export default function App({ Component, pageProps }: AppProps) {
  return (
    // <AuthProvider>
    // <ScopedCssBaseline>
    <>
      <QueryClientProvider client={queryClient}>
        <Component {...pageProps} />
      </QueryClientProvider>
      <ToastContainer limit={2} />
    </>
    // </ScopedCssBaseline>
    // </AuthProvider>
  );
}
