export const ROUTES = {
  LANDINGPAGE: "/",
  SIGNIN: "/login",
  APPS:"/apps",
  ACTIONS:"/actions",
  OVERVIEW:"/overview",
  EMPLOYEES:"/employees",
  ADD_EMPLOYEES:"/employees/add",
  INVENTORY_ASSETS:"/assets/inventory",
  MEMBERSHIP_ASSETS:"/assets/membership",
  ALL_ASSETS:"/assets/all",
  ADD_ASSETS:"/assets/all/add",
  PAYROLL:"/payroll",
  ADD_PAYROLL:"/payroll/add",
  CALENDAR:"/calendar",
  DOCUMENTS:"/documents",
  ADD_DOCUMENTS:"/documents/add",
  RECRUITMENT:"/recruitment",
  ROTAS:"/rotas",
  CLOCKIN:"/clockin",
  EXPENSES:"/expenses",
  SETTINGS:"/settings",
  HELP_CENTER:"/help-center",
};
