name: 🚀 Deploy on dev server

on: 
  push:
    branches:    
      - main 

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [21.x]
    
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@master
      with:
        node-version: ${{ matrix.node-version }}
    
    # - name: Copy .env.prod.example to .env
    #   run: cp .env.prod.example .env

    - name: 🔨 Build Project 
      run: |
        npm install
        npm run start
    
    - name: List output files
      run: find ./ -print

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.3
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./
