name: 🚀 Deploy on dev server

on: 
  push:
    branches:    
      - main 

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [21.x]
    
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@master
      with:
        node-version: ${{ matrix.node-version }}
    
    # - name: Copy .env.prod.example to .env
    #   run: cp .env.prod.example .env

    - name: 🔨 Build Project 
      run: |
        npm install
        npm run build
    
    - name: List output files
      run: find _next/ -print

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.3
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: _next/
        server-dir: /hr
        script: |
          cd /home/bespokecreatives/hr.bespokecreatives.tech
          git pull origin main
          # Copy the built files to your cPanel directory
          cp -R /home/bespokecreatives/hr.bespokecreatives.tech/_next /home/bespokecreatives/hr.bespokecreatives.tech
