name: Deploy wesite on push

on:
  push:
    branches:
      - ⁠main

jobs:
  web-deploy:
    name: Deploy
    
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Get latest code
      uses: actions/checkout@v2
      
      - name: Sync files
      uses: Samkirkland/FTP-Deploy-Action@4.1.0
      with:
        server: ftp.bespokecreatives.tech
        username: ${{secret.USERNAME}}
        password: ${{secret.PASSWORD}}
        server-dir: /
