name: Deploy Next.js to cPanel

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [21.x]
    
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@master
      with:
        node-version: ${{ matrix.node-version }}
  
    - name: Install dependencies
      run: npm install

    - name: Build Next.js app
      run: npm run build

    - name: Deploy to cPanel
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.CP_HOST }}
        username: ${{ secrets.CP_USERNAME }}
        password: ${{ secrets.CP_PASSWORD }}
        port: ${{ secrets.CP_PORT }}
        script: |
          cd /home/bespokecreatives/hr.bespokecreatives.tech
          git pull origin main
          # Copy the built files to your cPanel directory
          cp -R /home/bespokecreatives/hr.bespokecreatives.tech/.next /home/bespokecreatives/hr.bespokecreatives.tech
